language: go

go:
  - 1.11.x

before_install:
  - go get -u -v github.com/bdjimmy/gbind

script:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)

env: 
  global:
    secure: "${{secrets.codecov_token}}"
  
